#!/bin/bash

echo "🚀 African-004 Data Upload to Render"
echo "======================================"
echo ""

echo "📋 Instructions for uploading data to Render:"
echo ""
echo "1️⃣ First, access your Render dashboard:"
echo "   https://dashboard.render.com/web/srv-dpg-d25o0q3uibrs73aso9r0-a"
echo ""
echo "2️⃣ Open the shell for your backend service:"
echo "   - Click on your backend service"
echo "   - Go to the 'Shell' tab"
echo "   - Or use the web shell at:"
echo "   https://dashboard.render.com/web/srv-dpg-d25o0q3uibrs73aso9r0-a/shell"
echo ""
echo "3️⃣ In the Render shell, run these commands:"
echo ""
echo "   # Navigate to the correct directory"
echo "   cd backend/backend"
echo ""
echo "   # Create the admin user"
echo "   python manage.py shell"
echo ""
echo "   # In the Django shell, run:"
echo "   from django.contrib.auth import get_user_model"
echo "   User = get_user_model()"
echo "   user = User.objects.create_user(username='aman', email='a.kasa@alustudent.com', password='aman@123')"
echo "   user.role = 'ADMIN'"
echo "   user.is_staff = True"
echo "   user.is_superuser = True"
echo "   user.save()"
echo "   exit()"
echo ""
echo "4️⃣ Upload your local_data.json file:"
echo "   - In the Render shell, create the file:"
echo "   nano local_data.json"
echo "   # Copy and paste the content from your local local_data.json"
echo ""
echo "5️⃣ Load the data:"
echo "   python manage.py loaddata local_data.json"
echo ""
echo "6️⃣ Reset the admin password:"
echo "   python manage.py shell"
echo "   from django.contrib.auth import get_user_model"
echo "   User = get_user_model()"
echo "   user = User.objects.get(username='aman')"
echo "   user.set_password('aman@123')"
echo "   user.save()"
echo "   exit()"
echo ""
echo "🎯 Alternative: Use the Django Admin Panel"
echo "   - Go to: https://african-004-backend.onrender.com/admin/"
echo "   - Login with: admin / admin123 (if available)"
echo "   - Manually recreate your data through the admin interface"
echo ""
echo "🔗 Your application URLs:"
echo "   🌐 Frontend: https://african-004-frontend.onrender.com"
echo "   🔧 Backend: https://african-004-backend.onrender.com"
echo "   👨‍💼 Admin: https://african-004-backend.onrender.com/admin/"
echo ""
echo "📊 Expected data after upload:"
echo "   👥 Users: 3 (aman, manager1, staff1)"
echo "   📦 Inventory Items: 4 (Industrial Drill, Safety Gloves, etc.)"
echo "   🏭 Suppliers: 3 (ABC Industrial Supplies, etc.)"
echo "   📋 Orders: 3 (various purchase orders)"
echo ""
echo "✅ Once completed, you can log in with:"
echo "   👤 aman / aman@123 (Admin)"
echo "   👤 manager1 / Testpass123 (Manager)"
echo "   👤 staff1 / Testpass123 (Staff)" 